import { treeToString } from "./analyzers/structure";
import { type AssembledContext, getBudget, truncateToTokenBudget } from "./assembler";

function isRecentMerge(isoDate: string, days = 14): boolean {
  const parsed = Date.parse(isoDate);
  if (Number.isNaN(parsed)) return true;
  return parsed >= Date.now() - days * 24 * 60 * 60 * 1000;
}

export function renderHandoff(ctx: AssembledContext): string {
  const budget = getBudget(ctx.format);
  const sections: string[] = [];

  const lastCommit = ctx.git?.recentCommits[0];
  let header = `# HANDOFF — ${ctx.projectName}\n`;
  header += `> Generated by \`handoff-md\` at ${ctx.timestamp} | handoff-spec: ${ctx.specVersion}\n`;
  if (ctx.git) {
    header += `> Branch: \`${ctx.git.currentBranch}\``;
    if (lastCommit) {
      header += ` | Last commit: ${lastCommit.hash} ${lastCommit.message}`;
    }
    if (ctx.git.aheadBehind) {
      header += ` | ${ctx.git.aheadBehind}`;
    }
    header += "\n";
  }
  sections.push(truncateToTokenBudget(header, budget.header));

  if (ctx.sections.stack) {
    let stackSection = "## Stack\n";
    const showFramework =
      ctx.stack.framework !== "unknown" &&
      (ctx.format !== "compact" || ctx.stack.frameworkConfidence >= 0.9);
    const frameworkStr = showFramework ? `${ctx.stack.framework} + ` : "";
    const langStr = ctx.stack.language !== "unknown" ? ctx.stack.language : "";
    const pmStr = ctx.stack.packageManager !== "unknown" ? ctx.stack.packageManager : "";
    stackSection += `${[frameworkStr + langStr, pmStr].filter(Boolean).join(" | ")}\n`;
    const extras: string[] = [];
    if (ctx.stack.orm) extras.push(`ORM: ${ctx.stack.orm}`);
    if (ctx.stack.database) extras.push(`DB: ${ctx.stack.database}`);
    if (ctx.stack.auth) extras.push(`Auth: ${ctx.stack.auth}`);
    if (ctx.stack.deploy) extras.push(`Deploy: ${ctx.stack.deploy}`);
    if (ctx.stack.testing) extras.push(`Test: ${ctx.stack.testing}`);
    if (ctx.stack.linter) extras.push(`Lint: ${ctx.stack.linter}`);
    if (ctx.stack.moduleType) extras.push(`Module: ${ctx.stack.moduleType}`);
    if (ctx.stack.engines) extras.push(`Engines: ${ctx.stack.engines}`);
    if (extras.length > 0) {
      stackSection += `${extras.join(" | ")}\n`;
    }
    sections.push(truncateToTokenBudget(stackSection, budget.stack));
  }

  if (ctx.sections.scripts && ctx.scripts && ctx.scripts.scripts.length > 0) {
    let scriptsSection = "## Scripts\n";
    for (const s of ctx.scripts.scripts) {
      scriptsSection += `- \`${s.name}\`: ${s.command.slice(0, 80)}\n`;
    }
    sections.push(truncateToTokenBudget(scriptsSection, budget.scripts));
  }

  if (ctx.sections.workspace && ctx.workspace) {
    let wsSection = "## Workspace\n";
    wsSection += `${ctx.workspace.type}\n`;
    if (ctx.workspace.packages.length > 0) {
      wsSection += `Packages: ${ctx.workspace.packages.join(", ")}\n`;
    }
    sections.push(truncateToTokenBudget(wsSection, budget.workspace));
  }

  if (ctx.sections.ci && ctx.ci) {
    let ciSection = "## CI\n";
    ciSection += `Workflows: ${ctx.ci.workflows.join(", ")}\n`;
    if (ctx.ci.jobs.length > 0) {
      ciSection += `Jobs: ${ctx.ci.jobs.join(", ")}\n`;
    }
    sections.push(truncateToTokenBudget(ciSection, budget.ci));
  }

  if (ctx.sections.structure && ctx.structure.tree.length > 0) {
    let structSection = "## Structure\n```\n";
    structSection += treeToString(ctx.structure.tree);
    structSection += "\n```\n";
    if (ctx.structure.entryPoints.length > 0) {
      structSection += `Entry points: ${ctx.structure.entryPoints.join(", ")}\n`;
    }
    sections.push(truncateToTokenBudget(structSection, budget.structure));
  }

  if (ctx.sections.conventions && (ctx.structure.conventions.length > 0 || ctx.config)) {
    let convSection = "## Conventions\n";
    for (const conv of ctx.structure.conventions) {
      convSection += `- ${conv.category}: ${conv.pattern}\n`;
    }
    if (ctx.config && ctx.config.entries.length > 0) {
      for (const entry of ctx.config.entries) {
        convSection += `\n### AI Config (${entry.source})\n`;
        convSection += `${entry.lines.join("\n")}\n`;
      }
    } else if (ctx.config) {
      convSection += `\n### Existing AI Config (from ${ctx.config.configSource})\n`;
      convSection += `${ctx.config.existingInstructions.join("\n")}\n`;
    }
    const configBudget = ctx.config ? budget.config : 0;
    sections.push(truncateToTokenBudget(convSection, budget.conventions + configBudget));
  }

  if (ctx.sections.git && ctx.git && ctx.git.recentCommits.length > 0) {
    const maxCommits = ctx.format === "compact" ? 5 : ctx.format === "standard" ? 10 : 15;
    let activitySection = "## Recent Activity\n";

    if (
      ctx.git.lastMerge &&
      isRecentMerge(ctx.git.lastMerge.date ? `${ctx.git.lastMerge.date}T00:00:00Z` : "")
    ) {
      activitySection += `- Last merge: \`${ctx.git.lastMerge.hash}\` ${ctx.git.lastMerge.message}\n`;
    }

    for (const commit of ctx.git.recentCommits.slice(0, maxCommits)) {
      activitySection += `- \`${commit.hash}\` ${commit.message}`;
      if (commit.date) activitySection += ` (${commit.date})`;
      if (commit.files && commit.files.length > 0 && ctx.format === "full") {
        activitySection += ` — files: ${commit.files.slice(0, 5).join(", ")}`;
      }
      activitySection += "\n";
    }
    sections.push(truncateToTokenBudget(activitySection, budget.activity));
  }

  if (ctx.sections.git && ctx.git) {
    let stateSection = "## Current State\n";

    if (ctx.git.uncommittedChanges.length > 0) {
      stateSection += `**Uncommitted changes (${ctx.git.uncommittedChanges.length} files):**\n`;
      const maxChanges = ctx.format === "compact" ? 10 : 20;
      for (const change of ctx.git.uncommittedChanges.slice(0, maxChanges)) {
        stateSection += `- ${change}\n`;
      }
      if (ctx.git.uncommittedChanges.length > maxChanges) {
        stateSection += `- ... and ${ctx.git.uncommittedChanges.length - maxChanges} more\n`;
      }
    } else {
      stateSection += "Working tree is clean.\n";
    }

    if (ctx.git.activeBranches.length > 1) {
      stateSection += "\n**Active branches (last 7 days):**\n";
      for (const branch of ctx.git.activeBranches.slice(0, 5)) {
        const current = branch.name === ctx.git.currentBranch ? " ← current" : "";
        stateSection += `- \`${branch.name}\` (${branch.relativeDate})${current}\n`;
      }
    }

    if (ctx.git.conflictFiles.length > 0) {
      stateSection += "\n**⚠ Merge conflicts:**\n";
      for (const file of ctx.git.conflictFiles) {
        stateSection += `- ${file}\n`;
      }
    }

    sections.push(truncateToTokenBudget(stateSection, budget.state));
  }

  if (ctx.sections.todos && ctx.structure.todos.length > 0) {
    let issuesSection = "## Known Issues\n";
    for (const todo of ctx.structure.todos) {
      issuesSection += `- **${todo.type}** \`${todo.file}:${todo.line}\` ${todo.text}\n`;
    }
    sections.push(truncateToTokenBudget(issuesSection, budget.issues));
  }

  if (ctx.sections.env && ctx.structure.envVars.length > 0) {
    let envSection = "## Environment\n";
    envSection += `Required env vars: \`${ctx.structure.envVars.join("`, `")}\`\n`;
    sections.push(truncateToTokenBudget(envSection, budget.env));
  }

  if (ctx.warnings.length > 0) {
    let warnSection = "## Warnings\n";
    for (const w of ctx.warnings.slice(0, 5)) {
      warnSection += `- ${w}\n`;
    }
    sections.push(truncateToTokenBudget(warnSection, budget.warnings));
  }

  return sections.join("\n");
}
